FROM node:22-alpine AS build

WORKDIR /app

COPY mockup/frontend/package*.json ./
RUN npm install

COPY mockup/frontend/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY container/mockup/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80