"""auto_migration

Revision ID: f892bf659b0c
Revises: 
Create Date: 2026-04-25 04:32:50.013456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f892bf659b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_currency_id'), 'mst_currency', ['id'], unique=False)
    op.create_table('mst_sector',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mst_sector_id'), 'mst_sector', ['id'], unique=False)
    op.create_table('mst_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_stock_id'), 'mst_stock', ['id'], unique=False)
    op.create_table('trn_balance_sheet',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('treasury_shares_number', sa.Float(), nullable=True),
    sa.Column('ordinary_shares_number', sa.Float(), nullable=True),
    sa.Column('share_issued', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('tangible_book_value', sa.Float(), nullable=True),
    sa.Column('invested_capital', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('net_tangible_assets', sa.Float(), nullable=True),
    sa.Column('common_stock_equity', sa.Float(), nullable=True),
    sa.Column('total_capitalization', sa.Float(), nullable=True),
    sa.Column('total_equity_gross_minority_interest', sa.Float(), nullable=True),
    sa.Column('minority_interest', sa.Float(), nullable=True),
    sa.Column('stockholders_equity', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('capital_stock', sa.Float(), nullable=True),
    sa.Column('common_stock', sa.Float(), nullable=True),
    sa.Column('total_liabilities_net_minority_interest', sa.Float(), nullable=True),
    sa.Column('total_non_current_liabilities_net_minority_interest', sa.Float(), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('tradeand_other_payables_non_current', sa.Float(), nullable=True),
    sa.Column('non_current_deferred_taxes_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt_and_capital_lease_obligation', sa.Float(), nullable=True),
    sa.Column('long_term_provisions', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('other_current_liabilities', sa.Float(), nullable=True),
    sa.Column('current_debt_and_capital_lease_obligation', sa.Float(), nullable=True),
    sa.Column('current_provisions', sa.Float(), nullable=True),
    sa.Column('payables', sa.Float(), nullable=True),
    sa.Column('total_tax_payable', sa.Float(), nullable=True),
    sa.Column('accounts_payable', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_non_current_assets', sa.Float(), nullable=True),
    sa.Column('other_non_current_assets', sa.Float(), nullable=True),
    sa.Column('non_current_deferred_taxes_assets', sa.Float(), nullable=True),
    sa.Column('other_investments', sa.Float(), nullable=True),
    sa.Column('investmentin_financial_assets', sa.Float(), nullable=True),
    sa.Column('available_for_sale_securities', sa.Float(), nullable=True),
    sa.Column('financial_assets_designatedas_fair_value_through_profitor_loss_', sa.Float(), nullable=True),
    sa.Column('long_term_equity_investment', sa.Float(), nullable=True),
    sa.Column('investmentsin_joint_venturesat_cost', sa.Float(), nullable=True),
    sa.Column('investmentsin_associatesat_cost', sa.Float(), nullable=True),
    sa.Column('goodwill_and_other_intangible_assets', sa.Float(), nullable=True),
    sa.Column('other_intangible_assets', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('net_ppe', sa.Float(), nullable=True),
    sa.Column('accumulated_depreciation', sa.Float(), nullable=True),
    sa.Column('gross_ppe', sa.Float(), nullable=True),
    sa.Column('construction_in_progress', sa.Float(), nullable=True),
    sa.Column('other_properties', sa.Float(), nullable=True),
    sa.Column('machinery_furniture_equipment', sa.Float(), nullable=True),
    sa.Column('properties', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('assets_held_for_sale_current', sa.Float(), nullable=True),
    sa.Column('current_deferred_assets', sa.Float(), nullable=True),
    sa.Column('restricted_cash', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('finished_goods', sa.Float(), nullable=True),
    sa.Column('work_in_process', sa.Float(), nullable=True),
    sa.Column('raw_materials', sa.Float(), nullable=True),
    sa.Column('other_receivables', sa.Float(), nullable=True),
    sa.Column('taxes_receivable', sa.Float(), nullable=True),
    sa.Column('accounts_receivable', sa.Float(), nullable=True),
    sa.Column('cash_cash_equivalents_and_short_term_investments', sa.Float(), nullable=True),
    sa.Column('other_short_term_investments', sa.Float(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    op.create_table('trn_cash_flow',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('repurchase_of_capital_stock', sa.Float(), nullable=True),
    sa.Column('repayment_of_debt', sa.Float(), nullable=True),
    sa.Column('issuance_of_debt', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('end_cash_position', sa.Float(), nullable=True),
    sa.Column('beginning_cash_position', sa.Float(), nullable=True),
    sa.Column('effect_of_exchange_rate_changes', sa.Float(), nullable=True),
    sa.Column('changes_in_cash', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('net_other_financing_charges', sa.Float(), nullable=True),
    sa.Column('cash_dividends_paid', sa.Float(), nullable=True),
    sa.Column('net_common_stock_issuance', sa.Float(), nullable=True),
    sa.Column('common_stock_payments', sa.Float(), nullable=True),
    sa.Column('net_issuance_payments_of_debt', sa.Float(), nullable=True),
    sa.Column('net_long_term_debt_issuance', sa.Float(), nullable=True),
    sa.Column('long_term_debt_payments', sa.Float(), nullable=True),
    sa.Column('long_term_debt_issuance', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('net_other_investing_changes', sa.Float(), nullable=True),
    sa.Column('dividends_received_cfi', sa.Float(), nullable=True),
    sa.Column('net_investment_purchase_and_sale', sa.Float(), nullable=True),
    sa.Column('sale_of_investment', sa.Float(), nullable=True),
    sa.Column('purchase_of_investment', sa.Float(), nullable=True),
    sa.Column('net_business_purchase_and_sale', sa.Float(), nullable=True),
    sa.Column('sale_of_business', sa.Float(), nullable=True),
    sa.Column('purchase_of_business', sa.Float(), nullable=True),
    sa.Column('net_intangibles_purchase_and_sale', sa.Float(), nullable=True),
    sa.Column('sale_of_intangibles', sa.Float(), nullable=True),
    sa.Column('purchase_of_intangibles', sa.Float(), nullable=True),
    sa.Column('net_ppe_purchase_and_sale', sa.Float(), nullable=True),
    sa.Column('sale_of_ppe', sa.Float(), nullable=True),
    sa.Column('purchase_of_ppe', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('taxes_refund_paid', sa.Float(), nullable=True),
    sa.Column('interest_received_cfo', sa.Float(), nullable=True),
    sa.Column('interest_paid_cfo', sa.Float(), nullable=True),
    sa.Column('change_in_working_capital', sa.Float(), nullable=True),
    sa.Column('change_in_other_current_assets', sa.Float(), nullable=True),
    sa.Column('other_non_cash_items', sa.Float(), nullable=True),
    sa.Column('stock_based_compensation', sa.Float(), nullable=True),
    sa.Column('provisionand_write_offof_assets', sa.Float(), nullable=True),
    sa.Column('deferred_tax', sa.Float(), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=True),
    sa.Column('amortization_cash_flow', sa.Float(), nullable=True),
    sa.Column('depreciation', sa.Float(), nullable=True),
    sa.Column('net_foreign_currency_exchange_gain_loss', sa.Float(), nullable=True),
    sa.Column('gain_loss_on_sale_of_ppe', sa.Float(), nullable=True),
    sa.Column('net_income_from_continuing_operations', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    op.create_table('trn_financials',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('tax_effect_of_unusual_items', sa.Float(), nullable=True),
    sa.Column('tax_rate_for_calcs', sa.Float(), nullable=True),
    sa.Column('normalized_ebitda', sa.Float(), nullable=True),
    sa.Column('total_unusual_items', sa.Float(), nullable=True),
    sa.Column('total_unusual_items_excluding_goodwill', sa.Float(), nullable=True),
    sa.Column('net_income_from_continuing_operation_net_minority_interest', sa.Float(), nullable=True),
    sa.Column('reconciled_depreciation', sa.Float(), nullable=True),
    sa.Column('reconciled_cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('net_interest_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('interest_income', sa.Float(), nullable=True),
    sa.Column('normalized_income', sa.Float(), nullable=True),
    sa.Column('net_income_from_continuing_and_discontinued_operation', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('total_operating_income_as_reported', sa.Float(), nullable=True),
    sa.Column('diluted_average_shares', sa.Float(), nullable=True),
    sa.Column('basic_average_shares', sa.Float(), nullable=True),
    sa.Column('diluted_eps', sa.Float(), nullable=True),
    sa.Column('basic_eps', sa.Float(), nullable=True),
    sa.Column('diluted_ni_availto_com_stockholders', sa.Float(), nullable=True),
    sa.Column('net_income_common_stockholders', sa.Float(), nullable=True),
    sa.Column('otherunder_preferred_stock_dividend', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('minority_interests', sa.Float(), nullable=True),
    sa.Column('net_income_including_noncontrolling_interests', sa.Float(), nullable=True),
    sa.Column('net_income_continuous_operations', sa.Float(), nullable=True),
    sa.Column('tax_provision', sa.Float(), nullable=True),
    sa.Column('pretax_income', sa.Float(), nullable=True),
    sa.Column('special_income_charges', sa.Float(), nullable=True),
    sa.Column('other_special_charges', sa.Float(), nullable=True),
    sa.Column('write_off', sa.Float(), nullable=True),
    sa.Column('impairment_of_capital_assets', sa.Float(), nullable=True),
    sa.Column('net_non_operating_interest_income_expense', sa.Float(), nullable=True),
    sa.Column('total_other_finance_cost', sa.Float(), nullable=True),
    sa.Column('interest_expense_non_operating', sa.Float(), nullable=True),
    sa.Column('interest_income_non_operating', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('operating_expense', sa.Float(), nullable=True),
    sa.Column('other_operating_expenses', sa.Float(), nullable=True),
    sa.Column('research_and_development', sa.Float(), nullable=True),
    sa.Column('selling_general_and_administration', sa.Float(), nullable=True),
    sa.Column('selling_and_marketing_expense', sa.Float(), nullable=True),
    sa.Column('general_and_administrative_expense', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('operating_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    op.create_table('trn_income_stmt',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('earnings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    op.create_table('trn_quarterly_income_stmt',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('earnings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'code')
    )
    op.create_table('trn_stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('stock_market', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ma5', sa.Float(), nullable=True),
    sa.Column('ma25', sa.Float(), nullable=True),
    sa.Column('ma75', sa.Float(), nullable=True),
    sa.Column('upper2', sa.Float(), nullable=True),
    sa.Column('lower2', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('hist', sa.Float(), nullable=True),
    sa.Column('rsi14', sa.Float(), nullable=True),
    sa.Column('rsi28', sa.Float(), nullable=True),
    sa.Column('rci9', sa.Float(), nullable=True),
    sa.Column('rci26', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'stock_market', 'date', name='uq_trn_stock_price_code_market_date')
    )
    op.create_index(op.f('ix_trn_stock_price_date'), 'trn_stock_price', ['date'], unique=False)
    op.create_index(op.f('ix_trn_stock_price_id'), 'trn_stock_price', ['id'], unique=False)
    op.create_index(op.f('ix_trn_stock_price_stock_code'), 'trn_stock_price', ['stock_code'], unique=False)
    op.create_index(op.f('ix_trn_stock_price_stock_market'), 'trn_stock_price', ['stock_market'], unique=False)
    op.create_table('trn_white_list',
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('trading_unit', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('market', 'code')
    )
    op.create_table('mst_commodities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['mst_currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'market', name='uq_commodities_code_market')
    )
    op.create_index(op.f('ix_mst_commodities_id'), 'mst_commodities', ['id'], unique=False)
    op.create_table('trn_commodity_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('commodity_code', sa.String(length=32), nullable=False),
    sa.Column('commodity_market', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['mst_commodities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_id', 'date', name='uq_trn_commodity_price_code_market_date')
    )
    op.create_index(op.f('ix_trn_commodity_price_commodity_code'), 'trn_commodity_price', ['commodity_code'], unique=False)
    op.create_index(op.f('ix_trn_commodity_price_commodity_id'), 'trn_commodity_price', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_trn_commodity_price_commodity_market'), 'trn_commodity_price', ['commodity_market'], unique=False)
    op.create_index(op.f('ix_trn_commodity_price_date'), 'trn_commodity_price', ['date'], unique=False)
    op.create_index(op.f('ix_trn_commodity_price_id'), 'trn_commodity_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trn_commodity_price_id'), table_name='trn_commodity_price')
    op.drop_index(op.f('ix_trn_commodity_price_date'), table_name='trn_commodity_price')
    op.drop_index(op.f('ix_trn_commodity_price_commodity_market'), table_name='trn_commodity_price')
    op.drop_index(op.f('ix_trn_commodity_price_commodity_id'), table_name='trn_commodity_price')
    op.drop_index(op.f('ix_trn_commodity_price_commodity_code'), table_name='trn_commodity_price')
    op.drop_table('trn_commodity_price')
    op.drop_index(op.f('ix_mst_commodities_id'), table_name='mst_commodities')
    op.drop_table('mst_commodities')
    op.drop_table('trn_white_list')
    op.drop_index(op.f('ix_trn_stock_price_stock_market'), table_name='trn_stock_price')
    op.drop_index(op.f('ix_trn_stock_price_stock_code'), table_name='trn_stock_price')
    op.drop_index(op.f('ix_trn_stock_price_id'), table_name='trn_stock_price')
    op.drop_index(op.f('ix_trn_stock_price_date'), table_name='trn_stock_price')
    op.drop_table('trn_stock_price')
    op.drop_table('trn_quarterly_income_stmt')
    op.drop_table('trn_income_stmt')
    op.drop_table('trn_financials')
    op.drop_table('trn_cash_flow')
    op.drop_table('trn_balance_sheet')
    op.drop_index(op.f('ix_mst_stock_id'), table_name='mst_stock')
    op.drop_table('mst_stock')
    op.drop_index(op.f('ix_mst_sector_id'), table_name='mst_sector')
    op.drop_table('mst_sector')
    op.drop_index(op.f('ix_mst_currency_id'), table_name='mst_currency')
    op.drop_table('mst_currency')
    # ### end Alembic commands ###
